import path from "node:path";

import type {
  CodometerConfiguration,
  CodometerConfigurationContext,
  CodometerConfigurationFactory,
} from "@codometer/configuration";

/**
 * What this package is measured by, and the first example it ships.
 *
 * Its presence is the configuration-discovery example: the workspace root
 * already carries a
 * configuration that answers for every project beneath it, and codometer takes
 * the **first** file it finds walking upward — so this one replaces it
 * outright for this folder and everything under it. Nothing from the root file
 * is folded in, which is why the conventions below are restated rather than
 * imported.
 *
 * It is written as a factory for the same reason the root one is: one file
 * answers for more than one folder. Measuring the package measures the corpus
 * as a size-gated target; measuring anything beneath it — `examples/corpus/`,
 * which is
 * what nearly every example does — measures the files themselves, with the
 * conventions declared and no target to be empty.
 */

// ♟️ Conventions

/** Name of the target holding the sample corpus, and the join key its limit is written against. */
const CORPUS_TARGET_NAME = "Corpus";

/**
 * The conventions the corpus was built to demonstrate.
 *
 * Two file-pattern counters over a corpus with stated counts, and one symbol
 * counter beside them. The corpus holds four `*.service.ts` files, six
 * `*.unit.test.ts` files, and four static methods — three in the services and
 * one in the JavaScript sample, because a symbol counter walks both languages.
 * A reader can check the tool agrees before declaring a counter of their own.
 */
const conventions = [
  { label: "Service Files", patterns: ["**/*.service.ts"] },
  { label: "Unit Tests", patterns: ["**/*.unit.test.ts"] },
  {
    color: "166534",
    group: "typescript",
    label: "Static Methods",
    symbols: { kinds: ["method"], modifiers: ["static"] },
  },
] satisfies CodometerConfiguration["statistics"];

/**
 * What every run this package configures measures the same way.
 *
 * Python lives in a uv workspace here, so the interpreter is reached through
 * uv rather than being on PATH — which the `examples/python` configurations
 * cover, and which is directly reusable by
 * any repository whose Python is behind a virtual environment.
 */
const sharedConfiguration = {
  python: { command: "uv run python" },
  statistics: conventions,
} satisfies CodometerConfiguration;

/**
 * What a run measuring this package itself measures.
 *
 * The corpus is this package's equivalent of a compiled bundle: the thing it
 * ships, gated on its compressed size so a sample that grows without anybody
 * meaning it to is a failing check rather than a slow drift.
 */
const buildPackageConfiguration = (): CodometerConfiguration => ({
  ...sharedConfiguration,
  limits: [{ metric: `${CORPUS_TARGET_NAME}.size`, value: "12 KB" }],
  output: {
    markdown: {
      description:
        "Statistics for the sample corpus and the guides beside it, measured by [codometer](../codometer-cli), regenerated by `nx run codometer-examples:codometer:write`.",
      // Renamed for the reason this package documents: the README below
      // explains the default markers, so it holds `CODE_STATISTICS_START` in
      // its own prose and a run using the defaults would splice the block into
      // the middle of the sentence describing them. Any document about
      // codometer has to rename its own markers, and this is that document.
      endMarker: "<!-- SAMPLE_STATISTICS_END -->",
      path: "README.md",
      startMarker: "<!-- SAMPLE_STATISTICS_START -->",
    },
  },
  targets: [
    {
      analyses: ["size"],
      compression: "gzip",
      include: ["examples/corpus/**"],
      name: CORPUS_TARGET_NAME,
    },
  ],
});

/**
 * Everything codometer needs to know about this package in particular.
 *
 * A folder beneath the package — the corpus, or one of its language
 * directories — is measured with the conventions and nothing else. Declaring
 * the corpus target there too would leave it matching no files, and a limit
 * against an empty target fails the run, which `examples/limits` covers
 * rather than
 * something every other example should have to work around.
 */
const codometerConfiguration: CodometerConfigurationFactory = (
  context: CodometerConfigurationContext,
) =>
  path.resolve(context.directory) ===
  path.resolve(context.configurationDirectory)
    ? buildPackageConfiguration()
    : { ...sharedConfiguration };

export default codometerConfiguration;
