export { codometerConfigurationSchema } from "./modules/configuration/configuration-schema.constants";
// 📤 Exports
export {
  CODOMETER_ANALYSES,
  CODOMETER_COMMENT_LANGUAGES,
  CODOMETER_COMPRESSIONS,
  CODOMETER_DOCUMENTATION_UNITS,
  CODOMETER_FORMATS,
  CODOMETER_SEVERITIES,
  CODOMETER_STATISTIC_GROUPS,
  CODOMETER_SYMBOL_KINDS,
  CODOMETER_SYMBOL_MODIFIERS,
  CONFIGURATION_FILE_NAMES,
  ConfigurationFileNotFoundError,
  DEFAULT_CODEBASE_INPUT,
  DEFAULT_CUSTOM_STATISTIC_COLORS,
  DEFAULT_CUSTOM_STATISTIC_GROUP,
  DEFAULT_EXCLUDE_GLOBS,
  DEFAULT_INPUT_COMPRESSION,
  DEFAULT_INPUT_DIRECTORY,
  DEFAULT_INPUT_NAME,
  DEFAULT_JSON_INDENTATION,
  DEFAULT_LIMIT_SEVERITY,
  DEFAULT_MARKDOWN_END_MARKER,
  DEFAULT_MARKDOWN_START_MARKER,
  DEFAULT_PYTHON_COMMAND,
  InvalidConfigurationError,
  InvalidLimitValueError,
  MISSING_FORMAT_MESSAGE,
  REPOSITORY_ROOT_MARKERS,
  UnknownConfigurationFileTypeError,
} from "./modules/configuration/configuration.constants";
export { ConfigurationModule } from "./modules/configuration/configuration.module";
export { ConfigurationService } from "./modules/configuration/configuration.service";
export type {
  CodometerAnalysis,
  CodometerCommentLanguage,
  CodometerCommentMeasurement,
  CodometerCommentSelector,
  CodometerCompression,
  CodometerConfiguration,
  CodometerCustomStatistic,
  CodometerDocumentationUnit,
  CodometerFormat,
  CodometerInput,
  CodometerJsonOutput,
  CodometerLimit,
  CodometerMarkdownOutput,
  CodometerOutput,
  CodometerPythonConfiguration,
  CodometerSeverity,
  CodometerSymbolKind,
  CodometerSymbolMatcher,
  CodometerSymbolModifier,
  LoadConfigurationArguments,
} from "./modules/configuration/configuration.types";
export type {
  MarkdownAnchorHelpers,
  WriteMarkdownOutput,
  WriteMarkdownOutputArguments,
} from "./modules/configuration/output.types";

export type {
  LoadedConfiguration,
  ResolvedCodometerCommentSelector,
  ResolvedCodometerConfiguration,
  ResolvedCodometerCustomStatistic,
  ResolvedCodometerInput,
  ResolvedCodometerJsonOutput,
  ResolvedCodometerLimit,
  ResolvedCodometerMarkdownOutput,
  ResolvedCodometerOutput,
  ResolvedCodometerPythonConfiguration,
} from "./modules/configuration/resolved.types";
export type {
  CodeStatisticsResult,
  CodometerStatisticGroup,
  CssStatistics,
  CustomStatisticResult,
  CustomStatisticResultInstance,
  HclStatistics,
  JavascriptStatistics,
  JsonStatistics,
  JupyterStatistics,
  MarkdownStatistics,
  PythonStatistics,
  ShellStatistics,
  SqlStatistics,
  TomlStatistics,
  TypescriptStatistics,
  YamlStatistics,
} from "./modules/configuration/statistics.types";
export { InputModule } from "./modules/input/input.module";
export { InputService } from "./modules/input/input.service";
