// ♟️ Constants

/** Graph type `codependix-file-imports` builds, for either language. */
export const FILE_IMPORTS_GRAPH_TYPE = "fileImports";

/** `### <subheading>` placed above the TypeScript file-import graph's anchor. */
export const FILE_IMPORTS_MARKDOWN_SUBHEADING = "File Imports";

/**
 * The intro line placed under a newly auto-created `## 🕸️ Codependix`
 * heading — copied verbatim from the wording a human already placed by hand
 * in `packages/logger/README.md`, so an auto-created section reads exactly
 * like one a person wrote.
 */
export const MARKDOWN_SECTION_INTRO_LINE =
  "Dependency graphs exported by [codependix](https://github.com/JimmyPaolini/codebase/tree/main/packages/ic-suite/codependix/codependix-cli), regenerated by `nx run codebase:codependix:write`.";

/** Graph type `codependix-nestjs-modules` builds. */
export const NESTJS_MODULES_GRAPH_TYPE = "nestjsModules";

/** `### <subheading>` placed above the NestJS module graph's anchor. */
export const NESTJS_MODULES_MARKDOWN_SUBHEADING = "NestJS Module Graph";

/** Graph type `codependix-nx-projects` builds. */
export const NX_PROJECTS_GRAPH_TYPE = "nxProjects";

/** `### <subheading>` placed above an Nx Neighborhood's anchor. */
export const NX_PROJECTS_MARKDOWN_SUBHEADING = "Nx Neighborhood";

/**
 * `### <subheading>` placed above the Python file-import graph's anchor.
 *
 * `codependix-file-imports`'s Python builder shares `FILE_IMPORTS_GRAPH_TYPE`
 * with its TypeScript counterpart — a project is only ever one language, so
 * the two never collide over the same anchor — but each still renders under
 * its own subheading.
 */
export const PYTHON_IMPORTS_MARKDOWN_SUBHEADING = "Python File Imports";

/**
 * The `projectName` reported for the Workspace Graph's result.
 *
 * The Workspace Graph is not a real Nx project — it is exported once for the
 * whole repository — but `ProjectRunResult` is otherwise keyed by project
 * name, so this stands in for it wherever a result is reported.
 */
export const WORKSPACE_GRAPH_PROJECT_NAME = "workspace";
