// 📤 Exports
export {
  CODOMETER_STATISTIC_GROUPS,
  CODOMETER_SYMBOL_KINDS,
  CODOMETER_SYMBOL_MODIFIERS,
  codometerConfigurationSchema,
  CONFIGURATION_FILE_NAMES,
  DEFAULT_CUSTOM_STATISTIC_COLORS,
  DEFAULT_CUSTOM_STATISTIC_GROUP,
  DEFAULT_EXCLUDE_GLOBS,
  DEFAULT_JSON_INDENTATION,
  DEFAULT_MARKDOWN_END_MARKER,
  DEFAULT_MARKDOWN_START_MARKER,
  DEFAULT_PYTHON_COMMAND,
  UnknownConfigurationFileTypeError,
} from "./modules/configuration/configuration.constants";
export { ConfigurationFileNotFoundError } from "./modules/configuration/configuration.errors";
export { ConfigurationModule } from "./modules/configuration/configuration.module";
export { ConfigurationService } from "./modules/configuration/configuration.service";
export type {
  CodometerConfiguration,
  CodometerCustomStatistic,
  CodometerJsonOutputConfiguration,
  CodometerMarkdownOutputConfiguration,
  CodometerOutputConfiguration,
  CodometerPythonConfiguration,
  CodometerSymbolKind,
  CodometerSymbolMatcher,
  CodometerSymbolModifier,
  LoadConfigurationArguments,
  MarkdownAnchorHelpers,
  RenderMarkdownArguments,
  RenderMarkdownOutput,
  ResolvedCodometerConfiguration,
  ResolvedCodometerCustomStatistic,
  ResolvedCodometerJsonOutputConfiguration,
  ResolvedCodometerMarkdownOutputConfiguration,
  ResolvedCodometerOutputConfiguration,
  ResolvedCodometerPythonConfiguration,
  WriteMarkdownArguments,
  WriteMarkdownOutput,
} from "./modules/configuration/configuration.types";
export type {
  CodeStatisticsResult,
  CodometerStatisticGroup,
  CssStatistics,
  CustomStatisticResult,
  HclStatistics,
  JavascriptStatistics,
  JsonStatistics,
  JupyterStatistics,
  MarkdownStatistics,
  PythonStatistics,
  ShellStatistics,
  SqlStatistics,
  TomlStatistics,
  TypescriptStatistics,
  YamlStatistics,
} from "./modules/configuration/statistics.types";
