import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

import { Test } from "@nestjs/testing";
import { beforeAll, describe, expect, it } from "vitest";

import { MeanderGenerationModule } from "../meander-generation/meander-generation.module";
import { MotifPitchService } from "../meander-generation/motif-pitch.service";
import {
  MOSAIC_TILE_EDGE_BUDGET,
  MOSAIC_TILE_MAXIMUM_ROWS,
  MOSAIC_TILE_MINIMUM_ROWS,
} from "../mosaic-tile/mosaic-tile.constants";
import { COLUMNS_PER_SERPENTINE_UNIT } from "../parallel-motif/parallel-motif.constants";

import { LatticeIdentificationModule } from "./lattice-identification.module";
import { LatticeIdentificationService } from "./lattice-identification.service";

import type { Modifier } from "../meander-generation/meander-generation.types";
import type { MosaicTileShape } from "../mosaic-tile/mosaic-tile.types";

// 🔧 Configuration

/** Where `DrawCommand` writes the corpus, and where it is committed. */
const OUTPUT_DIRECTORY = path.join(import.meta.dirname, "../../../output");

/**
 * Every shape the `mosaic` half of the sweep commits a directory for,
 * derived from the family's own row range and edge budget rather than listed,
 * so a shape the budget starts or stops admitting arrives here without an
 * edit.
 */
const MOSAIC_SHAPES: readonly MosaicTileShape[] = Array.from(
  { length: MOSAIC_TILE_MAXIMUM_ROWS - MOSAIC_TILE_MINIMUM_ROWS + 1 },
  (_value, index) => MOSAIC_TILE_MINIMUM_ROWS + index,
).flatMap((rows) =>
  Array.from(
    {
      length: Math.max(Math.floor(MOSAIC_TILE_EDGE_BUDGET / (2 * rows - 3)), 1),
    },
    (_value, index) => ({ columns: index + 1, rows }),
  ),
);

/**
 * The two cross-family identities the corpus already holds, each naming a
 * `parallel` drawing and the `mosaic` tile it turns out to be.
 *
 * `serpentine` stacks its ribbons down the band rather than across it, so its
 * pitch is two columns whatever the ply — which is why a three-strand drawing
 * and a four-strand one are both read at a span of two, and why the `mosaic`
 * tiles they match are two columns wide.
 */
const CROSS_FAMILY_IDENTITIES: readonly {
  readonly modifier: Modifier;
  readonly mosaic: string;
  readonly parallel: string;
  readonly rows: number;
}[] = [
  {
    modifier: { name: "serpentine", offset: 1, strands: 3 },
    mosaic: "mosaic/3-rows/2-columns/56a9-zigzag.svg",
    parallel: "parallel/3-rows/serpentine-strands-3-offset-1-6-repeats.svg",
    rows: 3,
  },
  {
    modifier: { name: "serpentine", offset: 2, strands: 4 },
    mosaic: "mosaic/4-rows/2-columns/56a933.svg",
    parallel: "parallel/4-rows/serpentine-strands-4-offset-2-6-repeats.svg",
    rows: 4,
  },
];

/** One committed document, read off disk by its path relative to `output/`. */
const committed = async (name: string): Promise<string> =>
  readFile(path.join(OUTPUT_DIRECTORY, name), "utf8");

// 🧪 Tests

/**
 * What a reader of `output/` can already see, asserted.
 *
 * A `mosaic` drawing's filename is its address — `56a9-zigzag.svg` under
 * `3-rows/2-columns/` says which four points carry which direction bits — and
 * the enumeration that wrote those names never opened the file it wrote. So
 * addressing the committed documents back is the round trip that says the
 * name describes the ink rather than the intention, over all 8,551 of them at
 * once.
 *
 * The identities below are the same claim across a family boundary. A
 * `parallel` document and a `mosaic` document, generated by two motif
 * services that share no code, reduce to the same tile — which is the whole
 * point of addressing a meander by its lattice instead of by its family.
 */
describe("committed documents address to the names they are filed under", () => {
  let motifPitchService: MotifPitchService;
  let service: LatticeIdentificationService;

  beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [LatticeIdentificationModule, MeanderGenerationModule],
    }).compile();

    motifPitchService = await module.resolve(MotifPitchService);
    service = await module.resolve(LatticeIdentificationService);
  });

  it.each(MOSAIC_SHAPES)(
    "addresses every committed mosaic of $rows rows and $columns columns to its own filename",
    async ({ columns, rows }) => {
      const directory = path.join(
        OUTPUT_DIRECTORY,
        `mosaic/${rows}-rows/${columns}-columns`,
      );
      const listing = await readdir(directory);
      const fileNames = listing.toSorted();

      expect(fileNames.length).toBeGreaterThan(0);

      for (const fileName of fileNames) {
        const address = service.identifyDocument(
          await readFile(path.join(directory, fileName), "utf8"),
          columns,
        );
        const earned = address.subFamily ? `-${address.subFamily}` : "";

        expect({
          canonicalIdentifier: address.canonicalIdentifier,
          fileName: `${address.identifier}${earned}.svg`,
          shape: `${address.rows}r${address.columns}c`,
        }).toStrictEqual({
          canonicalIdentifier: address.identifier,
          fileName,
          shape: `${rows}r${columns}c`,
        });
      }
    },
  );

  it.each(CROSS_FAMILY_IDENTITIES)(
    "reads $parallel as the tile $mosaic is named for",
    async ({ modifier, mosaic, parallel, rows }) => {
      const columns = motifPitchService.columnSpan({
        modifier,
        rows,
        type: "parallel",
      });

      expect(columns).toBe(COLUMNS_PER_SERPENTINE_UNIT);

      const drawn = service.identifyDocument(
        await committed(parallel),
        columns,
      );
      const enumerated = service.identifyDocument(
        await committed(mosaic),
        columns,
      );
      const earned = drawn.subFamily ? `-${drawn.subFamily}` : "";

      expect(drawn.address).toBe(enumerated.address);
      expect(drawn.canonicalIdentifier).toBe(enumerated.canonicalIdentifier);
      expect(`${drawn.identifier}${earned}.svg`).toBe(path.basename(mosaic));
    },
  );

  it("states sameness through the canonical class while the literal address stays the name", async () => {
    // Four documents of one pattern, three of them `parallel` and one the
    // `mosaic` tile it turns out to be. Turning a ribbon over or rotating the
    // stack starts the same repeat at a different point, so each carries a
    // different literal address — which is what keeps four drawings four
    // names — and every one of them folds onto the same class.
    const addresses = await Promise.all(
      [
        "mosaic/4-rows/2-columns/56a933.svg",
        "parallel/4-rows/serpentine-strands-4-offset-1-6-repeats.svg",
        "parallel/4-rows/serpentine-strands-4-offset-2-6-repeats.svg",
        "parallel/4-rows/serpentine-strands-4-flip-alternating-offset-2-6-repeats.svg",
      ].map(async (name) =>
        service.identifyDocument(
          await committed(name),
          COLUMNS_PER_SERPENTINE_UNIT,
        ),
      ),
    );

    expect(
      new Set(addresses.map(({ canonicalIdentifier }) => canonicalIdentifier))
        .size,
    ).toBe(1);
    expect(new Set(addresses.map(({ identifier }) => identifier)).size).toBe(3);
  });
});
