services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    container_name: codebase-devcontainer
    privileged: true
    volumes:
      - ../..:/workspaces/codebase:cached
      - codebase-node-modules:/workspaces/codebase/node_modules
      - codebase-pnpm:/root/.local/share/pnpm
      - codebase-docker:/var/lib/docker
    env_file:
      # The codebase root level .env file (copied from .env.default in CI)
      - ../../.env
    deploy:
      resources:
        limits:
          memory: 6g
    command: sleep infinity

volumes:
  codebase-node-modules:
    name: codebase-node-modules
  codebase-pnpm:
    name: codebase-pnpm
  codebase-docker:
    name: codebase-docker
