// ♟️ Constants

/** Graph type `codependix-imports` builds. */
export const IMPORTS_GRAPH_TYPE = "imports";

/** `### <subheading>` placed above the file-level import graph's anchor. */
export const IMPORTS_MARKDOWN_SUBHEADING = "File Imports";

/**
 * The intro line placed under a newly auto-created `## 🕸️ Codependix`
 * heading — copied verbatim from the wording a human already placed by hand
 * in `packages/logger/README.md`, so an auto-created section reads exactly
 * like one a person wrote.
 */
export const MARKDOWN_SECTION_INTRO_LINE =
  "Dependency graphs exported by [codependix](https://github.com/JimmyPaolini/codebase/tree/main/packages/codependix-cli), regenerated by `nx run codebase:codependix:write`.";

/** Graph type `codependix-nestjs` builds. */
export const NESTJS_GRAPH_TYPE = "nestjs";

/** `### <subheading>` placed above the NestJS module graph's anchor. */
export const NESTJS_MARKDOWN_SUBHEADING = "NestJS Module Graph";

/** Graph type this ticket's `codependix-nx` package builds. */
export const NX_GRAPH_TYPE = "nx";

/** `### <subheading>` placed above an Nx Neighborhood's anchor. */
export const NX_MARKDOWN_SUBHEADING = "Nx Neighborhood";

/** Graph type `codependix-imports-python` builds. */
export const PYTHON_IMPORTS_GRAPH_TYPE = "pythonImports";

/** `### <subheading>` placed above the Python file-level import graph's anchor. */
export const PYTHON_IMPORTS_MARKDOWN_SUBHEADING = "Python File Imports";

/** Usage message shown when the command line names neither or both modes. */
export const USAGE_MESSAGE =
  "💡 Usage: codependix --check (or codependix --write)";

/**
 * The `projectName` reported for the Workspace Graph's result.
 *
 * The Workspace Graph is not a real Nx project — it is exported once for the
 * whole repository — but `ProjectRunResult` is otherwise keyed by project
 * name, so this stands in for it wherever a result is reported.
 */
export const WORKSPACE_GRAPH_PROJECT_NAME = "workspace";
