// Generated by `nx sync` from the conformetry configuration. Do not edit.

import { runConformetryGenerator } from "@jimmypaolini/conformetry-nx";

import type { Tree } from "@nx/devkit";

/**
 * Runs the `jupyter-notebook-application` conformetry generator.
 */
export async function jupyterNotebookApplication(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "jupyter-notebook-application",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-command-module` conformetry generator.
 */
export async function nestjsCommandModule(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-command-module",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-command-project` conformetry generator.
 */
export async function nestjsCommandProject(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-command-project",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-dataloader-module` conformetry generator.
 */
export async function nestjsDataloaderModule(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-dataloader-module",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-graphql-application` conformetry generator.
 */
export async function nestjsGraphqlApplication(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-graphql-application",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-graphql-module` conformetry generator.
 */
export async function nestjsGraphqlModule(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-graphql-module",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-service-file` conformetry generator.
 */
export async function nestjsServiceFile(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-service-file",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-service-module` conformetry generator.
 */
export async function nestjsServiceModule(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-service-module",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `nestjs-service-project` conformetry generator.
 */
export async function nestjsServiceProject(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "nestjs-service-project",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}

/**
 * Runs the `react-component` conformetry generator.
 */
export async function reactComponent(
  tree: Tree,
  options?: Record<string, unknown>,
): Promise<void> {
  await runConformetryGenerator({
    generatorName: "react-component",
    ...(options === undefined ? {} : { options }),
    tree,
  });
}
