import { type CallidescopeConfiguration } from "@callidescope/configuration";

/**
 * The report is published on main, and only the depth gate runs on a branch.
 *
 * A generated block in a tracked file has to be regenerated by whoever changes
 * the thing it describes, and this one changes on nearly every pull request.
 * Codometer already documents where that leads — every branch rewrites the same
 * block and conflicts with every other one — which is why it measures on main
 * instead. A call-stack block inherits that, and something worse: staleness
 * would fail every pull request whose call graph moved until the author reran
 * the writer, burying the depth findings the gate exists to surface.
 *
 * So the two are split at the flag rather than by leaving the destination unset.
 * `nx run codebase:callidescope:check` passes `--check depth`, which reads no
 * destination at all, so its exit code is purely the depth verdict.
 * `nx run codebase:callidescope:write` passes `--write`, and the release
 * workflow runs it on main. Two configurations carry that split with no third,
 * because the target hangs off nothing: `lint-codebase` does not depend on it,
 * so no run of it ever forwards `write` here, and the pull request names
 * `check` itself.
 *
 * Every rule and finding this configuration turns on has a worked example in
 * `packages/callidescope-examples`, which also demonstrates the opposite half
 * of the split above: it gates `reports` rather than `depth`, because its
 * traced source is frozen fixture code. `.callidescopeignore` keeps it out of
 * this run, because its fixtures exist to breach the limits set here.
 *
 * - `packages/callidescope-examples/README.md` — how to read a stack, and how
 *   to act on a depth, module-spread, or misplaced-callable finding.
 * - `packages/callidescope-examples/AGENTS.md` — a "callidescope reported X →
 *   open this example" table, for an agent handed a failing run.
 */
const callidescopeConfiguration: CallidescopeConfiguration = {
  excludeFrom: ["configuration/.callidescopeignore"],
  /**
   * `LoggerService` sits behind nearly every other callable in this
   * repository. A call to it is a fact about instrumentation, not about
   * how deep or wide the code around it is, and counting it would move
   * every other callable's depth and breadth on a change that has nothing
   * to do with them.
   */
  ignoreCallees: ["LoggerService.*"],
  output: {
    /**
     * A section in every traced project's own README.
     *
     * Published by `nx run codebase:callidescope:write` on main. Deliberately
     * not checked on pull requests: the block moves whenever the call graph
     * does, so gating on its freshness would fail branches for being out of
     * date with `main` rather than for anything they did.
     */
    projectReadmes: {},
  },
  limits: {
    /**
     * The deepest stack this repository currently has, so the gate starts
     * green and only fails on a regression past today's worst.
     *
     * A ratchet rather than a target. Set to the issue's suggested six, this
     * fails on arrival with 46 findings — which is a backlog, not a gate, and
     * a red pipeline nobody can act on teaches people to ignore it. Lower it
     * as the outliers come down; the distribution today runs
     * 19, 18, 17, 15, 14, 13, 13, 12, 12, 11, 11, then a tail at 10 and below.
     */
    maximumDepth: 19,
    spreadThreshold: 4,
  },
};

export default callidescopeConfiguration;
