import { type CallidescopeConfiguration } from "@callidescope/configuration";

/**
 * No output destination is configured on purpose.
 *
 * A generated block in a tracked file has to be regenerated by whoever changes
 * the thing it describes, and this one would change on nearly every pull
 * request. Codometer already documents where that leads — every branch rewrites
 * the same block and conflicts with every other one — which is why it measures
 * on main instead. A call-stack block would inherit that, and something worse:
 * `--check` would fail every pull request whose call graph moved until the
 * author reran `:write`, burying the depth violations it exists to surface.
 *
 * Leaving both destinations unset means nothing can be stale, so the exit code
 * of `nx run codebase:callidescope:check` is purely the violation verdict. The
 * writer and its staleness comparison are implemented and tested; naming a path
 * here is all it takes to turn them on.
 */
const callidescopeConfiguration: CallidescopeConfiguration = {
  excludeFrom: ["configuration/.callidescopeignore"],
  limits: {
    /**
     * The deepest stack this repository currently has, so the gate starts
     * green and only fails on a regression past today's worst.
     *
     * A ratchet rather than a target. Set to the issue's suggested six, this
     * fails on arrival with 46 findings — which is a backlog, not a gate, and
     * a red pipeline nobody can act on teaches people to ignore it. Lower it
     * as the outliers come down; the distribution today runs
     * 19, 18, 17, 15, 14, 13, 13, 12, 12, 11, 11, then a tail at 10 and below.
     */
    maximumDepth: 19,
    spreadThreshold: 4,
  },
};

export default callidescopeConfiguration;
