import { type CodometerConfiguration } from "@codometer/configuration";

/**
 * Everything codometer needs to know about this repository in particular.
 *
 * The measurement itself lives in `@codometer/cli` and knows nothing about
 * this workspace; add a `json` output destination here to have the statistics
 * written to a file as well as to the README badge block.
 */
const codometerConfiguration: CodometerConfiguration = {
  // Appended to the built-in exclusions (node_modules, dist, build, coverage,
  // .nx). The last two are ingested corpus and generated output rather than
  // authored source. They are committed, so `git ls-files` reports them, and
  // they are overwhelmingly markdown: left in, they supply 88% of the
  // repository's markdown files and bury every prose metric under the data
  // payload. `markdownlint` and `cspell` already ignore both for the same
  // reason.
  exclude: [
    "**/notepads/**",
    "**/templates/**",
    "applications/lexico-ingestion/data/**",
    "applications/affirmations/output/**",
  ],
  output: {
    markdown: {
      description:
        "Repository statistics measured by [codometer](packages/codometer-cli), regenerated by `nx run codebase:codometer`.",
      path: "README.md",
    },
  },
  // Python lives in a uv workspace, so the interpreter is reached through uv
  // rather than being on PATH.
  python: { command: "uv run python" },
};

export default codometerConfiguration;
