import { type CodometerConfiguration } from "@codometer/configuration";

/**
 * Everything codometer needs to know about this repository in particular.
 *
 * The measurement itself lives in `@codometer/cli` and knows nothing about
 * this workspace; add a `json` output destination here to have the statistics
 * written to a file as well as to the README badge block.
 */
const codometerConfiguration: CodometerConfiguration = {
  // What this repository does not measure lives in an ignore file, the way
  // every other tool here keeps its exclusions. Files git never tracked are
  // already absent — discovery enumerates through `git ls-files` — so the
  // ignore file only has to name what is committed but generated.
  excludeFrom: ["configuration/.codometerignore"],
  output: {
    markdown: {
      description:
        "Repository statistics measured by [codometer](packages/codometer-cli), regenerated by `nx run codebase:codometer`.",
      path: "README.md",
    },
  },
  // Python lives in a uv workspace, so the interpreter is reached through uv
  // rather than being on PATH.
  python: { command: "uv run python" },
};

export default codometerConfiguration;
