name: 📊 Report Coverage
description: Uploads test or type coverage reports depending on the executed target

inputs:
  target:
    description: The matrix check target being run
    required: true
  is-failure:
    description: Whether the workflow run has failed
    required: true

runs:
  using: composite
  steps:
    - name: 📊 Upload Type Coverage
      if: inputs.is-failure == 'true' && inputs.target == 'typecheck-code'
      uses: actions/upload-artifact@v7
      with:
        name: type-coverage-reports
        path: |
          applications/*/type-coverage-report.txt
          packages/*/type-coverage-report.txt
          tools/*/type-coverage-report.txt
        retention-days: 30

    - name: 📊 Upload Test Coverage
      if: inputs.target == 'test-code'
      uses: actions/upload-artifact@v7
      with:
        name: coverage-reports
        path: |
          coverage/
          applications/**/coverage/
          packages/**/coverage/
          tools/**/coverage/
        retention-days: 30
