// ♟️ Constants

/** Where the emitted plugin is written, relative to the workspace root. */
export const DEFAULT_OUTPUT_PATH = "tools/conformetry-generators";

/** Header warning readers that a file is emitted and will be overwritten. */
export const GENERATED_FILE_NOTICE =
  "// Generated by `nx sync` from the conformetry configuration. Do not edit.";

/** Message `nx sync:check` prints when the emitted plugin is stale. */
export const OUT_OF_SYNC_MESSAGE =
  "The conformetry generator plugin is out of sync with the conformetry configuration.";

/** Indent width for emitted JSON, matching the workspace formatter. */
export const JSON_INDENT = 2;

/** Package name the emitted plugin is addressed by in `nx g <name>:<gen>`. */
export const DEFAULT_PACKAGE_NAME = "@jimmypaolini/conformetry-generators";

/** The JSON schema editors validate an emitted `generators.json` against. */
export const GENERATORS_SCHEMA_PATH =
  "node_modules/@nx/devkit/src/generators/generators-schema.json";
